방 만드는 페이지 퍼블리싱
2023-Summer-Bootcamp-TeamD/frontend pull request #10
Opened 2023-07-12 07:43 UTC by tjrmswo

## 추가한 기능 설명

방 만드는 페이지 UI 구성 완료

## check list

- [ ] issue number를 브랜치 앞에 추가 하였는가?
- [ ] 모든 단위 테스트를 돌려보고 기존에 작동하던 테스트에 영향이 없는 것을 확인했는가?

2023-07-12 08:08 UTC, Leeseunghwan7305 requested changes
퍼블리싱하시느라 고생 많으셨니다 !
피드백남겨주신거 수정후 다시 풀리퀘날려주세여 !

2023-07-12 08:08 UTC, Leeseunghwan7305 commented on src/components/NavBar.jsx
> +export default NavBar;
여기 폴더가 jsx로 되어있는데 tsx로 수정해주시거나 삭제해주세요 !

2023-07-12 08:08 UTC, Leeseunghwan7305 commented on src/pages/CreatingSpecificRooms/index.tsx
> +const index = () => {
컴포넌트 이름은 index가 아니라 다른 이름으로 지어주세요 !

2023-07-12 08:08 UTC, Leeseunghwan7305 commented on src/pages/CreatingSpecificRooms/index.tsx
> +  right: 2em;
웬만하면 flex 나 grid로 레이아웃 잡아주시고
애매한 레이아웃만 absolute 써주세요 !

2023-07-12 08:11 UTC, tjrmswo commented on src/components/NavBar.jsx
> +export default NavBar;
이거 삭제했었는데 깃허브 작업하는 과정에서 다시 추가된 것 같습니다 지금 삭제했습니다

2023-07-13 06:06 UTC, tjrmswo commented on src/pages/CreatingSpecificRooms/index.tsx
> +const index = () => {
변경했습니다

2023-07-13 06:06 UTC, tjrmswo commented on src/pages/CreatingSpecificRooms/index.tsx
> +  right: 2em;
수정했습니다!

2023-07-14 08:49 UTC, closed without merging