[feat/#13] 입장페이지 피드백 반영 수정
2023-Summer-Bootcamp-TeamD/frontend pull request #14
Opened 2023-07-12 15:02 UTC by jihye9549

1. interface -> type 변경
2. css 일부 수정
3. 변수명 변경
4. maxlength 수정

2023-07-12 19:22 UTC, Kimyebin00 approved these changes
저는 더 수정할 거 없어보입니다!! 그리고 pr에 리뷰 남겨주신 거 수정할 때는 기존 브랜치에서 수정하고 다시 푸시하면 된다고 하셨어요. 참고하십숑 제가 처음에 잘못해가지구 ㅎㅎ...

2023-07-13 04:36 UTC, jihye9549 commented
앗 감사합니다 !!

2023-07-13 05:57 UTC, Leeseunghwan7305 requested changes
코드는 깔끔하게 잘 짜셨는데 컴포넌트 이름을 바꿔주셨으면 좋겠습니다 !
현재 컴포넌트 이름이 Button Label인데 다른 팀원들과 머지하고 나중에 봤을떄 혼동이 올꺼같아요!
저라면 EntranceButton <- 이런식으로 할꺼같네요 !

2023-07-13 06:05 UTC, tjrmswo approved these changes
저도 수정 사항은 없어 보이니다 아주 잘하신 것 같습니다!

2023-07-13 06:36 UTC, jihye9549 commented
확인했습니다!!☺️

2023-07-17 05:31 UTC, jihye9549 commented
다 수정했습니다 !!

2023-07-17 05:51 UTC, Leeseunghwan7305 approved these changes

2023-07-17 06:14 UTC, merged