[feat/#15] 그림페이지 퍼블리싱
2023-Summer-Bootcamp-TeamD/frontend pull request #19
Opened 2023-07-14 04:47 UTC by jihye9549

## 추가한 기능 설명

그림페이지 퍼블리싱 완료

## check list

- [ ✅ ] issue number를 브랜치 앞에 추가 하였는가?
- [ ✅ ] 모든 단위 테스트를 돌려보고 기존에 작동하던 테스트에 영향이 없는 것을 확인했는가?

2023-07-14 06:37 UTC, Kimyebin00 requested changes
typescript 잘 쓰시네요 저는... 여전히 js 나 다름 없는 거 같은 ㅋㅋㅋ ㅜ

2023-07-14 06:37 UTC, Kimyebin00 commented on src/pages/DrawingResult/index.tsx
> +  </Category>
저번에 이런 느낌으로 제가 급훈 컴포넌트 만들 때, 
<급훈> 
  <급훈 타이틀 /> 
  <급훈 내용 /> 
</급훈> 
이런 식으로 상세히 나눴었거든요?? 
그때 승환님께서 너무 쪼개는 것도 안 좋다고 쪼개지 말고, styled components 에서 자식 접근자 사용 가능하니까 그걸로 css 하라고 하셨어요. 
이것도 그렇게 하는 게 좋지 않을까 하는...!

2023-07-14 06:37 UTC, Kimyebin00 commented on src/pages/DrawingResult/index.tsx
> +  //background: #41d319;
주석 제거 해주세용

2023-07-14 06:38 UTC, jihye9549 commented on src/pages/DrawingResult/index.tsx
> +  //background: #41d319;
넹💗

2023-07-16 03:50 UTC, Leeseunghwan7305 requested changes
고생하셨씁니다 !!

2023-07-16 03:50 UTC, Leeseunghwan7305 commented on src/common/DrawingHeader /index.tsx
> +const CircleText = ['우', '리', '의', '작', '품'];
이런 더미데이터는 constans폴더안에 쓰고 export 해주세요 !

2023-07-16 03:50 UTC, Leeseunghwan7305 commented on src/pages/DrawingResult/index.tsx
> +];
여기도요 !

2023-07-17 05:27 UTC, Leeseunghwan7305 approved these changes

2023-07-17 05:36 UTC, Kimyebin00 approved these changes

2023-07-17 06:16 UTC, merged