[Feat/#43] 방 생성 페이지 api 연동
2023-Summer-Bootcamp-TeamD/frontend pull request #47
Opened 2023-07-20 16:13 UTC by tjrmswo

## 추가한 기능 설명
방 생성 페이지 api 연동 성공.
그리고 게임 페이지로 
닉네임, 카테고리, 시간, 인원 수를 useNavigate로 전달.
<br>

## check list

- [ ] issue number를 브랜치 앞에 추가 하였는가?
- [ ] 모든 단위 테스트를 돌려보고 기존에 작동하던 테스트에 영향이 없는 것을 확인했는가?

2023-07-20 16:44 UTC, Kimyebin00 requested changes
수고하셨습니다!! 저랑 다른 부분들도 좀 있어서 비교해보고 좋았어요👍🏻👍🏻

2023-07-20 16:44 UTC, Kimyebin00 commented on src/pages/CreatingSpecificRooms/index.tsx
> +  }, [category]);
이건 사용자 입장에선 필요없지 않을까요?! 보통 개발자 도구를 켜고 웹 이용하진 않으니까요

css로 뭐 선택했는지 보여주면 좋을 거 같아요 저는 hover 하면 배경색 바뀌는 거처럼 선택하면 배경색 바뀌는 식으로 했어요!! 이건 근재님 방식대로 원하는 거 하시면 될 거 같아용

2023-07-20 16:44 UTC, Kimyebin00 commented on src/pages/CreatingSpecificRooms/index.tsx
> +  ];
GamInfo -> GameInfo 오타 있구요

게임 페이지로 닉네임, 제한 시간, 입장 인원, 입장코드(uuid) 이렇게 보내야 돼요! uuid 는 api 호출 response로 받으니까 아래 api 호출 코드 아래에다가 정의하시면 될 거 같아용

그리고 전 배열 내에 객체 여러 개 말고, 그냥 객체로 gameInfo 정의했거든요?! 뭐 해도 상관 없긴 할 텐데 배열 내에 객체 여러 개 하면 두 번 꺼내 써야 하니까 그냥 객체로 넣는 것도 좋을 거 같아요!

2023-07-20 16:44 UTC, Kimyebin00 commented on src/pages/CreatingSpecificRooms/index.tsx
> +  const selectGenre = (event: React.MouseEvent<HTMLDivElement>) => {
위에 category 라고 상태 정의해두셨으니까, selectCategory 로 하면 더 좋을 거 같아요!

2023-07-21 03:13 UTC, Leeseunghwan7305 reviewed
api연동 처음이시면 많이 어려우실텐데 잘 짜신것같습니다 !
2주남았는데 파이팅합시다 !

2023-07-21 03:13 UTC, Leeseunghwan7305 commented on src/pages/CreatingSpecificRooms/index.tsx
>        setPersonnel(personnel + 1);
사소한거긴한데 리액트 훅이랑 함수랑 한줄 띄우면 한눈에 봤을떄 가독성이 더 좋아질꺼같아요 !
20번쨰줄이랑 21번쨰줄 사이를 한칸 띄워주세요~

2023-07-21 03:13 UTC, Leeseunghwan7305 commented on src/pages/CreatingSpecificRooms/index.tsx
> +  };
axios자체를 함수로 빼서 사용하면 좀 더 tsx파일에서 ui로직을 한눈에 집중해서 볼수있거든요 ! 
제가 머지한 코드는 api폴더에 따로 분리해놨는데 참고하시면 좋을것같습니다 !

2023-07-22 06:07 UTC, closed without merging