[feat/#3] Header 퍼블리싱 및 assets 추가
2023-Summer-Bootcamp-TeamD/frontend pull request #6
Opened 2023-07-11 08:41 UTC by Kimyebin00

## 추가한 기능 설명
1. Header 퍼블리싱
- 급훈
- 시계
- 태극기

2. assets 추가
- 퍼블리싱에 필요한 asset 추가
- 시계 이미지, 태극기 이미지
<br>

## check list

- 

- [✅] issue number를 브랜치 앞에 추가 하였는가?

- [✅] 모든 단위 테스트를 돌려보고 기존에 작동하던 테스트에 영향이 없는 것을 확인했는가?

2023-07-11 09:10 UTC, Leeseunghwan7305 requested changes
고생하셨습니다 ! 이쁘게 잘 짜주셨네요 !

2023-07-11 09:10 UTC, Leeseunghwan7305 commented on src/common/NavBar/index.tsx
> +                    <span style={{ fontSize: '4rem' }}>어차피 1등은 D팀</span>
inline 방식으로 css적용하시는것도 좋은데
styled-componets 문법중에 nesting 써주시면 더 좋을꺼같아요 !

2023-07-11 09:10 UTC, Leeseunghwan7305 commented on src/common/NavBar/index.tsx
> +    height: 20vh;
nav바 height는 px로 해주세요 !

2023-07-11 09:10 UTC, Leeseunghwan7305 commented on src/common/NavBar/index.tsx
> +    //left:45vw;
필요없는 코드 , 주석은 지워주세요 !

2023-07-11 15:01 UTC, Kimyebin00 commented on src/common/NavBar/index.tsx
> +                    <span style={{ fontSize: '4rem' }}>어차피 1등은 D팀</span>
변경했습니다!

2023-07-11 15:01 UTC, Kimyebin00 commented on src/common/NavBar/index.tsx
> +    height: 20vh;
변경했습니다!

2023-07-11 15:01 UTC, Kimyebin00 commented on src/common/NavBar/index.tsx
> +    //left:45vw;
변경했습니다!

2023-07-12 05:46 UTC, tjrmswo approved these changes
아주 좋습니다!

2023-07-12 07:10 UTC, merged