[feat/#58] 게임 결과 페이지 api 연동
2023-Summer-Bootcamp-TeamD/frontend pull request #61
Opened 2023-07-24 19:32 UTC by Kimyebin00

## 추가한 기능 설명
1. 게임 결과 페이지 api 연동 - msw 사용
2. response로 상장 및 석차 메모 값 넣기
<br>

## check list

- [ ] issue number를 브랜치 앞에 추가 하였는가?
- [ ] 모든 단위 테스트를 돌려보고 기존에 작동하던 테스트에 영향이 없는 것을 확인했는가?

2023-07-24 21:47 UTC, Leeseunghwan7305 requested changes
고생하셨습니다 ! msw 잘 되네영 :)

2023-07-24 21:47 UTC, Leeseunghwan7305 commented on src/pages/GameResult/index.tsx
> +    if (ranking.length !== 0) {
length가 0 이라면 ranking도 자연스럽게 false 처리가 되어서 !ranking 이라고 적어주셔도 되는데 참고만 해주세요 ! 뭐가 더 좋다 나쁘다는 없는거같아용~!

2023-07-24 21:47 UTC, Leeseunghwan7305 commented on src/pages/GameResult/index.tsx
> +                  }
여기는 UI로직이라  개인적으로 최대한 짧고 간결하게 하는게 중요하다고 생각이 드는데  스타일드 컴포넌트에서 삼항연사자쓰면서 해도 무방할꺼같네요 !

2023-07-25 00:02 UTC, Kimyebin00 commented on src/pages/GameResult/index.tsx
> +    if (ranking.length !== 0) {
넵!!

2023-07-25 00:02 UTC, Kimyebin00 commented on src/pages/GameResult/index.tsx
> +                  }
수정했습니다!

2023-08-01 15:42 UTC, merged